config/routes.rb
Fmstool::Application.routes.draw do
  resources :algorithms


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/fms/algorithm.rb
class Fms::Algorithm < ActiveRecord::Base
	extend Fms::Extensions

	has_one :detection, :class_name => 'Fms::Algorithm::Detection', :dependent => :destroy 
	has_one :response, :class_name => 'Fms::Algorithm::Response', :dependent => :destroy 
	has_one :source_text, :class_name => 'Fms::Algorithm::SourceText', :dependent => :destroy   
	attr_accessible :identifier, :title, :subtype, :category, :fault_class, :mission_phase, :description
end

app/models/fms/algorithm/detection.rb
class Fms::Algorithm::Detection < ActiveRecord::Base
	belongs_to :algorithm
	has_many :steps, :class_name => 'Fms::Algorithm::DetectionStep', :dependent => :destroy
	extend Fms::Extensions
	attr_accessible :frequency_category, :frequency, :indications_to_verify_fault, :checks_until_reset, :is_enabled, :record_history, :alert_ground_on_detection, :alert_ground_on_verification
end

app/models/fms/algorithm/detection_step.rb
class Fms::Algorithm::DetectionStep < ActiveRecord::Base
	belongs_to :detection, :class_name => 'Fms::Algorithm::Detection'
	extend Fms::Extensions
	attr_accessible :order, :title, :category, :mnemonic, :threshold_high, :threshold_low, :description
end

app/models/fms/algorithm/response.rb
class Fms::Algorithm::Response < ActiveRecord::Base
	belongs_to :algorithm
	has_many :steps, :class_name => 'Fms::Algorithm::ResponseStep', :dependent => :destroy
	extend Fms::Extensions
	attr_accessible :is_enabled, :priority
	has_extensions :enables, :disables, :mucks_with
end

app/models/fms/algorithm/response_step.rb
class Fms::Algorithm::ResponseStep < ActiveRecord::Base
	belongs_to :response, :class_name => 'Fms::Algorithm::Response'
	extend Fms::Extensions
	attr_accessible :order, :title, :category, :execution_delay, :execution_time, :command, :opcode, :parameters, :description
end

app/models/fms/algorithm/source_text.rb
class Fms::Algorithm::SourceText < ActiveRecord::Base
	belongs_to :algorithm

	attr_accessible :content, :checksum  
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController
  # GET /algorithms
  # GET /algorithms.json
  def index
    @algorithms = Algorithm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @algorithms }
    end
  end

  # GET /algorithms/1
  # GET /algorithms/1.json
  def show
    @algorithm = Algorithm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @algorithm }
    end
  end

  # GET /algorithms/new
  # GET /algorithms/new.json
  def new
    @algorithm = Algorithm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @algorithm }
    end
  end

  # GET /algorithms/1/edit
  def edit
    @algorithm = Algorithm.find(params[:id])
  end

  # POST /algorithms
  # POST /algorithms.json
  def create
    @algorithm = Algorithm.new(params[:algorithm])

    respond_to do |format|
      if @algorithm.save
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully created.' }
        format.json { render json: @algorithm, status: :created, location: @algorithm }
      else
        format.html { render action: "new" }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /algorithms/1
  # PUT /algorithms/1.json
  def update
    @algorithm = Algorithm.find(params[:id])

    respond_to do |format|
      if @algorithm.update_attributes(params[:algorithm])
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algorithms/1
  # DELETE /algorithms/1.json
  def destroy
    @algorithm = Algorithm.find(params[:id])
    @algorithm.destroy

    respond_to do |format|
      format.html { redirect_to algorithms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/views/algorithms/_form.html.erb
<%= simple_form_for(@algorithm) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :identifier %>
    <%= f.input :type %>
    <%= f.input :subtype %>
    <%= f.input :fault_class %>
    <%= f.input :title %>
    <%= f.input :detections_to_verify %>
    <%= f.input :detection_checks_until_reset %>
    <%= f.input :detection_enabled %>
    <%= f.input :response_enabled %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/algorithms/edit.html.erb
<h1>Editing algorithm</h1>

<%= render 'form' %>

<%= link_to 'Show', @algorithm %> |
<%= link_to 'Back', algorithms_path %>

app/views/algorithms/index.html.erb
<h1>Listing algorithms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Identifier</th>
    <th>Type</th>
    <th>Subtype</th>
    <th>Fault class</th>
    <th>Title</th>
    <th>Detections to verify</th>
    <th>Detection checks until reset</th>
    <th>Detection enabled</th>
    <th>Response enabled</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @algorithms.each do |algorithm| %>
  <tr>
    <td><%= algorithm.name %></td>
    <td><%= algorithm.identifier %></td>
    <td><%= algorithm.type %></td>
    <td><%= algorithm.subtype %></td>
    <td><%= algorithm.fault_class %></td>
    <td><%= algorithm.title %></td>
    <td><%= algorithm.detections_to_verify %></td>
    <td><%= algorithm.detection_checks_until_reset %></td>
    <td><%= algorithm.detection_enabled %></td>
    <td><%= algorithm.response_enabled %></td>
    <td><%= algorithm.description %></td>
    <td><%= link_to 'Show', algorithm %></td>
    <td><%= link_to 'Edit', edit_algorithm_path(algorithm) %></td>
    <td><%= link_to 'Destroy', algorithm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Algorithm', new_algorithm_path %>

app/views/algorithms/new.html.erb
<h1>New algorithm</h1>

<%= render 'form' %>

<%= link_to 'Back', algorithms_path %>

app/views/algorithms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @algorithm.name %>
</p>

<p>
  <b>Identifier:</b>
  <%= @algorithm.identifier %>
</p>

<p>
  <b>Type:</b>
  <%= @algorithm.type %>
</p>

<p>
  <b>Subtype:</b>
  <%= @algorithm.subtype %>
</p>

<p>
  <b>Fault class:</b>
  <%= @algorithm.fault_class %>
</p>

<p>
  <b>Title:</b>
  <%= @algorithm.title %>
</p>

<p>
  <b>Detections to verify:</b>
  <%= @algorithm.detections_to_verify %>
</p>

<p>
  <b>Detection checks until reset:</b>
  <%= @algorithm.detection_checks_until_reset %>
</p>

<p>
  <b>Detection enabled:</b>
  <%= @algorithm.detection_enabled %>
</p>

<p>
  <b>Response enabled:</b>
  <%= @algorithm.response_enabled %>
</p>

<p>
  <b>Description:</b>
  <%= @algorithm.description %>
</p>


<%= link_to 'Edit', edit_algorithm_path(@algorithm) %> |
<%= link_to 'Back', algorithms_path %>